title: Home
description: >-
  Hamba yang tidak berguna di tangan Allah yang penuh hikmat.
baseurl: ""
url: "https://deo.or.id"
permalink: /:year/:title:output_ext
paginate: 7
paginate_path: "/:num"
hidden: true
timezone: Asia/Singapore

plugins:
  - jekyll-asciidoc
  - jekyll-redirect-from
  - jekyll-feed

author: Deo Valiandro. M

asciidoctor:
  attributes:
    - icons=font
    - source-highlighter=rouge
    - sectanchors=_
    - experimental=_
    - rouge-style=github
    - stylesdir=css

markdown: kramdown
highlighter: rouge
render_with_liquid: false
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter_opts:
    block:
      line_numbers: false

feed:
  posts_limit: 1000
