title: Home
description: "Sabbe Sattā Bhavantu Sukhitattā"
url: "https://deovaliandro.github.io"
permalink: /:year/:title:output_ext
hidden: true
timezone: Asia/Makassar
author: Deo Valiandro. M

plugins:
  - jekyll-asciidoc
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-email-protect

asciidoctor:
  attributes:
    - icons=font
    - source-highlighter=rouge
    - sectanchors=_
    - experimental=_
    - rouge-style=github
    - stylesdir=css

markdown: kramdown
highlighter: rouge
render_with_liquid: false
kramdown:
  input: GFM
  hard_wrap: true
  syntax_highlighter_opts:
    default_lang: html
    css_class : 'syntax'
    block:
      line_numbers: true

feed:
  posts_limit: 1000

sass:
  sass_dir: _sass
  style: compressed