title: deo
description: >- 
  soliter
baseurl: ""
url: "https://deovaliandro.github.io"
author: Deo Valiandro. M
permalink: /:year/:month/:day/:title:output_ext

plugins:
  - jekyll-asciidoc
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-katex

asciidoctor:
  attributes:
    - icons=font
    - source-highlighter=rouge
    - source-linenums-option=_
    - sectanchors=_
    - experimental=_
    - rouge-style=github
    - stylesdir=css

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  math_engine: katex

katex:
  rendering_options:
    throw_error: true
    error_color: "#cc0000"