title: Deo
description: >- 
  soliter
baseurl: ""
url: "https://deovaliandro.github.io"
footer: "&copy;
        Deo Valiandro. M -- <mdv16h@gmail.com>, 2016 -- 2021 \\|
        [Github](https://github.com/deovaliandro) \\|
        [Twitter](https://twitter.com/deovaliandro) \\|
        [RSS](/feed.xml)"
author: Deo Valiandro. M
license: >
    Text and figures are licensed under [Creative Commons Attribution CC BY
    4.0](https://creativecommons.org/licenses/by/4.0/). The source code is
    licensed under MIT.

plugins:
  - jekyll-asciidoc
  - jekyll-redirect-from
  - jekyll-feed

asciidoctor:
  attributes:
    - icons=font
    - source-highlighter=rouge
    - source-linenums-option=_
    - sectanchors=_
    - experimental=_
    - rouge-style=github
    - stylesdir=css

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false