title: 0.0.0.0
description: >- 
  soliterme
baseurl: ""
url: "https://deovaliandro.github.io"
footer: "&copy;
        Deo Valiandro. M -- <valiandrod@gmail.com>, 2016 -- 2021 \\|
        [Github](https://github.com/deovaliandro) \\|
        [Twitter](https://twitter.com/deovaliandro) \\|
        [RSS](/feed.xml)"

plugins:
  - jekyll-asciidoc
  - jekyll-redirect-from
  - jekyll-feed

asciidoctor:
  attributes:
    - icons=font
    - source-highlighter=rouge
    - source-linenums-option=_
    - sectanchors=_
    - experimental=_
    - rouge-style=github
    - stylesdir=css

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false