name: CI
on:
  push:
    branches:
    - main

jobs:
  CI:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.7'

    - run: bundle install && bundle exec jekyll build

    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.7.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: _site
        force_orphan: true
