name: CI
on:
  push:
    branches:
    - main

jobs:
  CI:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.7'

    - run: bundle install && bundle exec jekyll build

    - name: Install Minify deb package on Ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: apt-get update && apt-get install --no-install-recommends --yes minify

    - name: Minify HTML files
      run: |
        minify --type=html --recursive --output "./" --match=\.html "./_site/" \
        --html-keep-conditional-comments \
        --html-keep-default-attrvals \
        --html-keep-document-tags \
        --html-keep-end-tags \
        --html-keep-quotes \
        --verbose

    - name: Minify JSON files
      run: |
        minify --type=json --recursive --output "./" --match=\.json "./_site/" --verbose || true

    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.7.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: _site
        force_orphan: true
