name: CI
on:
  push:
    branches:
    - master

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '3.0'

    - run: bundle install && bundle exec jekyll build
